### ISSUE TITLE
Describing a CF stack results in exception

### ISSUE THREAD

**Issue by janost** [baliame/awsc#6]
```
Traceback (most recent call last):
  File "/home/janost/.local/bin/awsc", line 33, in <module>
    sys.exit(load_entry_point('awsc==0.1.0', 'console_scripts', 'awsc')())
  File "/home/janost/.local/lib/python3.9/site-packages/awsc-0.1.0-py3.9.egg/awsc/main.py", line 105, in main
  File "/home/janost/.local/lib/python3.9/site-packages/awsc-0.1.0-py3.9.egg/awsc/common.py", line 42, in main
  File "/home/janost/.local/lib/python3.9/site-packages/awsc-0.1.0-py3.9.egg/awsc/termui/ui.py", line 180, in main
  File "/home/janost/.local/lib/python3.9/site-packages/awsc-0.1.0-py3.9.egg/awsc/termui/block.py", line 80, in input
  File "/home/janost/.local/lib/python3.9/site-packages/awsc-0.1.0-py3.9.egg/awsc/termui/list_control.py", line 52, in input
  File "/home/janost/.local/lib/python3.9/site-packages/awsc-0.1.0-py3.9.egg/awsc/resource_lister.py", line 152, in describe
  File "/home/janost/.local/lib/python3.9/site-packages/awsc-0.1.0-py3.9.egg/awsc/resource_lister.py", line 313, in opener
TypeError: __init__() missing 1 required positional argument: 'sg_entry'
```

**Comment by baliame** [comment]
Fixed
